server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ms_user?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop

spring.rabbitmq.addresses=amqps://vprmqrka:X9XP2vone0LbqKH54m94kgWxY5oPhNv_@jackal.rmq.cloudamqp.com/vprmqrka

broker.queue.email.name=default.email